---
# git configuration

- name: git | customizing git
  become: no
  shell: git config --global {{ item }}
  with_items:
    - alias.co checkout
    - alias.ci commit
    - alias.st status
    - alias.br branch
    - color.branch auto
    - color.diff auto
    - color.interactive auto
    - color.status auto
    - branch.autosetuprebase always
    - push.default current
    - core.mergeoptions --no-edit
    - color.status always
    - color.ui auto

- name: git | setting up git global username
  become: no
  shell: git config --global user.name {{ git.username }}

- name: git | setting up git global email
  become: no
  shell: git config --global user.email {{ git.email }}
