---
# ImageMagick

- name: imagemagick | install imagemagick
  become: yes
  become_user: root
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - imagemagick
