---
# MySQL

- name: mysql | installing mysql
  apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
  become: yes
  become_user: root
  with_items:
    - mysql-server
    - mysql-client
    - libmysqlclient-dev
    - python-mysqldb

- name: mysql | update mysql root password for all root accounts
  become: yes
  become_user: root
  mysql_user: >
    name=root
    password=root
    priv=*.*:ALL
    state=present
    host=localhost
